### ISSUE TITLE
Grep isn't reading/responding to the output of fastboot oem unlock command

### ISSUE THREAD

**Issue by willhubs** [samuelcaldas/Bruteforce-Bootloader-Unlocker#1]
ADB and Fastboot installed, usb debugging enabled.

Rebooted phone into bootloader using
adb -d reboot bootloader

./bootloader_unlocker 

Current device: ZY3285J6KE
Your unlock code is: 1000000000000000
Saving...
~$

Running manually:
fastboot oem unlock 1000000000000000
                                                   (bootloader) Code validation failure with status 7
OKAY [  0.011s]
Finished. Total time: 0.011s

Appears that it's not reading the failure part of the response from fastboot oem unlock 1000000000000000

**Comment by samuelcaldas** [comment]
Hi @username,

Thank you for reporting the issue!

We've identified the problem and have implemented a fix in the latest version of the script. The error you encountered with reading the failure part of the Fastboot response should now be resolved.

Please download the latest version of the code from the repository, and try running the script again. If the issue persists or you encounter any new problems, kindly let us know, and we’ll continue to investigate.

We appreciate your feedback and patience!

Best regards,  
Samuel Caldas
